apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: dogukant/fastapi # Docker Hub'daki image
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql+psycopg://postgres:02021997a@postgres/productmanagement"
      initContainers: # Alembic migration için init container
      - name: alembic-migrate
        image: dogukant/fastapi
        command: ["alembic", "upgrade", "head"]
        env:
        - name: DATABASE_URL
          value: "postgresql+psycopg://postgres:02021997a@postgres/productmanagement"
        - name: SECRET_KEY
          value: "09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7"
        - name: ALGORITHM
          value: "HS256"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30001 # Minikube için sabit port