name: Deploy FastAPI Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to Kubernetes
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: dogukant/fastapi
      DEPLOYMENT_NAME: fastapi-deployment
      NAMESPACE: default

    steps:
    # 1. Repo'yu Checkout Et
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Docker Build ve Push
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t dogukant/fastapi:latest .
        docker push dogukant/fastapi:latest

    # # 3. Kubernetes'e Deploy Et
    # - name: Set up kubectl
    #   uses: azure/setup-kubectl@v3
    #   with:
    #     version: 'latest'

    # - name: Deploy to Kubernetes
    #   run: |
    #     echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig
    #     export KUBECONFIG=kubeconfig

    #     kubectl set image deployment/$DEPLOYMENT_NAME fastapi-container=$IMAGE_NAME:latest -n $NAMESPACE
    #     kubectl rollout restart deployment/$DEPLOYMENT_NAME -n $NAMESPACE
    #     kubectl rollout status deployment/$DEPLOYMENT_NAME -n $NAMESPACE
